/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************

Bare metal project to blink an LED on the Black Pill board.  The LED is on GPIO Port C, Pin 13

Outline:
1) Enable GPIOPC clock, which is on AHB1
2) Clear the P13 pin mode



 */

#include <stdint.h>
#include "stm32f4xx.h"

#define GPIOC_EN		(1 << 2)  		// Enable bit 2 to turn on GPIOC 0n the AHB1 bus
#define P13CLR			(00 << 26)		//
#define P13OUTPUT		(01 << 26)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC->AHB1ENR |= GPIOC_EN;  		// Enable GPIOC clock

	GPIOC->MODER &= ~P13CLR;  		// Clear pin mode for Pin 13
	GPIOC->MODER |= P13OUTPUT;		// Set pin 13 to output mode

    /* Loop forever */
	for(;;);
}
